title: "GroSS: Group-Size Series Decomposition for Grouped Architecture Search"
description: A decomposition method which allows for simultaneous training of an entire search space of group convolution architectures.
url: gross.active.vision
signoff: Henry Howard-Jenkins

links:
  - name: <strong>AVLCode</strong>
    url: https://code.active.vision
    external: true
  - name: <strong>GitHub</strong>
    url: https://github.com/ActiveVisionLab/GroSS
    external: true

permalink: pretty
