OUT_DIR: "./weights/vgg/imagenet/wang-et-al/search/ft_under-orig"
MODEL:
  LOAD_PATH: "weights/vgg/imagenet/wang-et-al/gross/decompose/0/decompnet_0.pth"
  INIT_DECOMPOSED: True
  FUSE_FOR_TRAIN: True
  BACKBONE: "VGG-ImageNet"
  DECOMPOSABLE_LAYERS: ["conv1_2", "conv2_1", "conv2_2", "conv3_1", "conv3_2", "conv3_3", "conv4_1", "conv4_2", "conv4_3", "conv5_1", "conv5_2", "conv5_3"]
  DECOMPOSE_STRUCTURE: [[11], [5, 10], [1, 7, 14, 28], [3, 9, 18], [15, 30, 60], [16, 32, 64], [16, 32, 64], [29, 58, 116], [3, 33, 66], [7, 28, 56, 112], [7, 28, 56, 112], [7, 28, 56, 112]]
  BOTTLE_DIMS: [[11, 18], [10, 24], [28, 28], [36, 48], [60, 48], [64, 56], [64, 100], [116, 100], [132, 132], [224, 224], [224, 224], [224, 224]]
DATASET:
  NAME: "imagenet"
  ROOT_DIR: "./data/imagenet"
  NORM_MEAN: [0.485, 0.456, 0.406]
  NORM_VAR: [0.229, 0.224, 0.225]
  INPUT_SIZE: (3, 224, 224)
TRAIN:
  BATCH_SIZE: 128
  GROUP_SIZES: [11, 10, 14, 9, 15, 32, 64, 58, 3, 56, 7, 7]
  FREEZE_STANDARD_LAYERS: False
  NUM_RUNS: 1
  NUM_EPOCHS: 14
  LR_MILESTONES: [8, 12]
  LR_GAMMA: 0.1
  INITIAL_LR: 0.0005
  SAVE_AT_START: True
  SAVE_EVERY: 1
  LOSS_LABEL: "vgg/imagenet/shallow/ft_loss"
  ACC_LABEL: "vgg/imagenet/shallow/ft_accuracy"
  EARLY_STOPPING: True
TEST:
  GROUP_SIZES: [11, 10, 14, 9, 15, 32, 64, 58, 3, 56, 7, 7]
  BATCH_SIZE: 256
DECOMPOSITION:
  MIN_STEP: 1e-5