OUT_DIR: "./weights/resnet/ft_16"
MODEL:
  LOAD_PATH: "./weights/resnet/decompose/0/decompnet_0.pth"
  INIT_DECOMPOSED: True
  FUSE_FOR_TRAIN: True
  BACKBONE: "ResNet18"
  DECOMPOSABLE_LAYERS: ["conv2_1", "conv2_2", "conv2_3", "conv2_4", "conv3_1", "conv3_2", "conv3_3", "conv3_4", "conv4_1", "conv4_2", "conv4_3", "conv4_4", "conv5_1", "conv5_2", "conv5_3", "conv5_4"]
  DECOMPOSE_STRUCTURE: [[1, 4, 16, 32], [1, 4, 16, 32], [1, 4, 16, 32], [1, 4, 16, 32], [1, 4, 16, 32], [1, 4, 16, 32], [1, 4, 16, 32], [1, 4, 16, 32], [1, 4, 16, 32], [1, 4, 16, 32], [1, 4, 16, 32], [1, 4, 16, 32], [1, 4, 16, 32], [1, 4, 16, 32], [1, 4, 16, 32], [1, 4, 16, 32]]
DATASET:
  NAME: "imagenet"
  ROOT_DIR: "./data/imagenet"
  NORM_MEAN: [0.485, 0.456, 0.406]
  NORM_VAR: [0.229, 0.224, 0.225]
  INPUT_SIZE: (3, 224, 224)
TRAIN:
  BATCH_SIZE: 512
  GROUP_SIZES: [16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16]
  FREEZE_STANDARD_LAYERS: False
  FREEZE_BN_LAYERS: False
  NUM_RUNS: 1
  NUM_EPOCHS: 12
  LR_MILESTONES: [8, 10]
  LR_GAMMA: 0.1
  INITIAL_LR: 0.001
  SAVE_AT_START: True
  EARLY_STOPPING: True
  SAVE_EVERY: 1
  LOSS_LABEL: "resnet/ft_loss"
  ACC_LABEL: "resnet/ft_accuracy(16)"
TEST:
  GROUP_SIZES: [16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16]
  BATCH_SIZE: 1024